import { useEffect, useRef } from "react";
import useStore from "@/store/useStore";
import { ArrowLeft } from "lucide-react";
import { ShieldCheck } from "lucide-react";

const TermsPage = () => {
  const setRoute = useStore((state) => state.setRoute);
  const containerRef = useRef(null);

  useEffect(() => {
    if (window.gsap) {
      window.gsap.fromTo(
        containerRef.current,
        { opacity: 0, y: 20 },
        { opacity: 1, y: 0, duration: 0.8, ease: "power3.out" },
      );
    }
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-dvh bg-[#fdfdfd] dark:bg-black text-zinc-900 dark:text-zinc-100 py-12 px-6">
      <div ref={containerRef} className="max-w-3xl mx-auto space-y-12">
        <button
          onClick={() => setRoute("landing")}
          className="flex items-center gap-2 text-zinc-500 hover:text-zinc-900 dark:hover:text-white transition-colors group cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          Back to Home
        </button>

        <header className="space-y-4 text-left">
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 bg-zinc-100 dark:bg-zinc-900 rounded-2xl flex items-center justify-center">
              <ShieldCheck className="w-8 h-8 text-zinc-900 dark:text-white" />
            </div>
            <h1 className="text-4xl md:text-5xl font-heading tracking-tight">
              Terms of Service
            </h1>
          </div>
          <p className="text-zinc-500 dark:text-zinc-400 text-sm">
            Last updated: April 19, 2026
          </p>
        </header>

        <section className="prose prose-zinc dark:prose-invert max-w-none space-y-8">
          <div className="p-6 bg-rose-50 dark:bg-rose-500/10 border border-rose-100 dark:border-rose-500/20 rounded-3xl">
            <h2 className="text-rose-600 dark:text-rose-400 text-lg font-bold mt-0">
              Personal Use Only
            </h2>
            <p className="text-rose-700/80 dark:text-rose-300/80 m-0">
              FrameFetch is a personal project created for educational and
              entertainment purposes. It is strictly for{" "}
              <strong>personal use only</strong>. Using images generated by this
              tool for commercial purposes is prohibited.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-bold">1. Acceptance of Terms</h2>
            <p>
              By accessing FrameFetch, you agree to be bound by these Terms of
              Service. This is a "just for fun" mockup studio designed for sharing
              beautifully framed music lyrics, players, and social media posts.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-bold">2. No Commercial Use</h2>
            <p>
              FrameFetch is not a commercial product. We do not charge for its
              use, and you may not use the output of this application to
              generate revenue. All logos (Apple Music, Spotify, X/Twitter) belong to their
              respective owners.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-bold">3. Intellectual Property</h2>
            <p>
              We do not claim ownership of the music metadata, album artwork, or
              lyrics provided through third-party APIs (iTunes, LRCLib). These
              belong to the respective copyright holders. FrameFetch is a
              framing tool and does not host or distribute music files.
            </p>
          </div>

          <div className="space-y-4 text-center pt-12 text-zinc-400 text-sm italic">
            FrameFetch is not affiliated with Apple Inc., Spotify AB, or X Corp.
          </div>
        </section>
      </div>
    </div>
  );
};

export default TermsPage;
